name: CMake
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      # Use the Docker image as published in your GitHub Container Registry
      image: ghcr.io/${{ github.repository }}/ubuntu-24.04-with-tools:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE --parallel $(nproc)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: build/*.uf2

  release:
    name: Create Release (if tag pushed)
    permissions:
      contents: write
      packages: read
    # This job runs only when the ref is a tag
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/${{ github.repository }}/ubuntu-24.04-with-tools:latest

    steps:
      # Download the firmware which were previously built
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: artefacts
      # Create a release and upload it as a release to this repository
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          updateOnlyUnreleased: true
          tag: ${{ github.ref_name }}
          # Attach the files as part of the release.
          artifacts: |
            artefacts/*.uf2
